// import { useRouter } from 'next/navigation';

import Link from 'next/link';

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// };
import { Provider } from '@/components/ui/provider';

export default function RootLayout({ children }) {
  // const router = useRouter();

  return (
    <html lang='en' suppressHydrationWarning>
      <body>
        {/* <nav>
          <button onClick={() => router.push('/counter')}>counter</button>
          <button onClick={() => router.push('/todo')}>todo</button>
        </nav> */}
        <Provider>
          <nav>
            <Link href='/'>Home</Link>
            <Link href='/counter'>Counter</Link>
            <Link href='/todo'>Todo</Link>
          </nav>
          {children}
        </Provider>
      </body>
    </html>
  );
}
