// import { useRouter } from 'next/navigation';

import { Center, Link as ChakraLink, HStack, VStack } from '@chakra-ui/react';
import Link from 'next/link';

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// };
import { Provider } from '@/components/ui/provider';
import { Container } from '@chakra-ui/react';

export default function RootLayout({ children }) {
  // const router = useRouter();

  return (
    <html lang='en' suppressHydrationWarning>
      <body>
        {/* <nav>
          <button onClick={() => router.push('/counter')}>counter</button>
          <button onClick={() => router.push('/todo')}>todo</button>
        </nav> */}
        <Provider>
          <Container>
            <Center>
              <VStack>
                <nav>
                  <HStack>
                    <ChakraLink asChild variant='underline' color='blue.400'>
                      <Link href='/'>home</Link>
                    </ChakraLink>
                    <ChakraLink asChild variant='underline' color='blue.400'>
                      <Link href='/counter'>counter</Link>
                    </ChakraLink>
                    <ChakraLink asChild variant='underline' color='blue.400'>
                      <Link href='/todo'>todo</Link>
                    </ChakraLink>
                  </HStack>
                </nav>
                {children}
              </VStack>
            </Center>
          </Container>
        </Provider>
      </body>
    </html>
  );
}
